import { Order, OrderUpdate, OrderMessage, OrderSpecification, User } from '@/types';

export const DEMO_USER: User = {
  id: 'user_demo_001',
  email: 'john@techstartup.com',
  full_name: 'John Martinez',
  company_name: 'TechStartup Inc',
  role: 'client',
  client_role: 'owner',
  organization_id: 'user_demo_001',
  parent_user_id: null,
  invited_by: null,
  invite_status: 'active',
  created_at: '2025-01-15T10:00:00Z',
};

export const DEMO_ADMIN: User = {
  id: 'user_admin_001',
  email: 'admin@swaggy.com',
  full_name: 'Sarah Chen',
  company_name: 'Swaggy',
  role: 'admin',
  client_role: 'owner',
  organization_id: 'user_admin_001',
  parent_user_id: null,
  invited_by: null,
  invite_status: 'active',
  created_at: '2024-01-01T00:00:00Z',
};

export const DEMO_ORDERS: Order[] = [
  {
    id: 'order_001',
    client_id: 'user_demo_001',
    status: 'delivered',
    product_type: 'Apparel',
    product_description: 'Custom branded t-shirts with embroidered logo',
    quantity: 500,
    target_price: 8.5,
    target_delivery_date: '2026-02-15',
    notes: 'Employee swag for company retreat. Standard fit, 100% cotton.',
    created_at: '2025-11-20T09:30:00Z',
    updated_at: '2026-03-10T14:22:00Z',
  },
  {
    id: 'order_002',
    client_id: 'user_demo_001',
    status: 'in_transit',
    product_type: 'Drinkware',
    product_description: 'Stainless steel water bottles with custom print',
    quantity: 250,
    target_price: 12.0,
    target_delivery_date: '2026-04-30',
    notes: 'Client appreciation gifts. 16oz capacity, color options: blue, white, black.',
    created_at: '2026-01-08T11:45:00Z',
    updated_at: '2026-04-05T16:30:00Z',
  },
  {
    id: 'order_003',
    client_id: 'user_demo_001',
    status: 'sample_approval_pending',
    product_type: 'Bags & Totes',
    product_description: 'Canvas tote bags with screen-printed design',
    quantity: 1000,
    target_price: 5.75,
    target_delivery_date: '2026-06-15',
    notes: 'Marketing conference giveaway. Reinforced stitching, natural canvas material.',
    created_at: '2026-02-22T13:15:00Z',
    updated_at: '2026-04-08T10:00:00Z',
  },
  {
    id: 'order_004',
    client_id: 'user_demo_001',
    status: 'sourcing',
    product_type: 'Tech Accessories',
    product_description: 'USB-C charging cables with branded sleeves',
    quantity: 750,
    target_price: 3.25,
    target_delivery_date: '2026-08-01',
    notes: 'Trade show merchandise. Quality cables, braided nylon sleeves with logo.',
    created_at: '2026-03-18T08:20:00Z',
    updated_at: '2026-04-09T11:45:00Z',
  },
];

export const DEMO_UPDATES: OrderUpdate[] = [
  {
    id: 'update_001',
    order_id: 'order_001',
    status: 'delivered',
    message: 'Your order has been successfully delivered! All 500 t-shirts are in perfect condition.',
    created_by: 'user_admin_001',
    created_at: '2026-03-10T14:22:00Z',
    requires_action: false,
  },
  {
    id: 'update_002',
    order_id: 'order_002',
    status: 'in_transit',
    message: 'Your shipment left the warehouse and is now in transit. Tracking number: FEDEX123456789',
    created_by: 'user_admin_001',
    created_at: '2026-04-05T16:30:00Z',
    requires_action: false,
  },
  {
    id: 'update_003',
    order_id: 'order_002',
    status: 'packing',
    message: 'Quality check completed successfully. Order is now being packed for shipment.',
    created_by: 'user_admin_001',
    created_at: '2026-03-28T09:15:00Z',
    requires_action: false,
  },
  {
    id: 'update_004',
    order_id: 'order_003',
    status: 'sample_approval_pending',
    message: 'Sample production complete! We have sent you 3 sample tote bags for approval. Please review and confirm within 3 business days.',
    created_by: 'user_admin_001',
    created_at: '2026-04-08T10:00:00Z',
    requires_action: true,
    action_type: 'sample_approval',
  },
  {
    id: 'update_005',
    order_id: 'order_003',
    status: 'sample_production',
    message: 'Samples are being produced. Expected completion: April 8, 2026',
    created_by: 'user_admin_001',
    created_at: '2026-04-01T14:30:00Z',
    requires_action: false,
  },
  {
    id: 'update_006',
    order_id: 'order_004',
    status: 'sourcing',
    message: 'We are currently identifying the best suppliers for USB-C cables. We have found 3 potential options and are comparing quality and pricing.',
    created_by: 'user_admin_001',
    created_at: '2026-04-09T11:45:00Z',
    requires_action: false,
  },
  {
    id: 'update_007',
    order_id: 'order_004',
    status: 'sourcing',
    message: 'We need clarification on your logo design placement. Should the branding be centered or positioned in the top corner of the sleeve?',
    created_by: 'user_admin_001',
    created_at: '2026-04-06T08:30:00Z',
    requires_action: true,
    action_type: 'info_needed',
  },
];

export const DEMO_MESSAGES: OrderMessage[] = [
  {
    id: 'msg_001',
    order_id: 'order_003',
    sender_id: 'user_demo_001',
    sender_role: 'client',
    message: 'These samples look great! Can we adjust the ink color to be slightly darker? It seems a bit faded.',
    attachments: [],
    created_at: '2026-04-09T14:20:00Z',
  },
  {
    id: 'msg_002',
    order_id: 'order_003',
    sender_id: 'user_admin_001',
    sender_role: 'admin',
    message: 'Absolutely! We will request a new batch of samples with darker ink color. This should take 2-3 business days.',
    attachments: [],
    created_at: '2026-04-09T15:45:00Z',
  },
  {
    id: 'msg_003',
    order_id: 'order_004',
    sender_id: 'user_demo_001',
    sender_role: 'client',
    message: 'For the sleeve placement, I think centered would look better. Also, can you send me a quote for 750 units?',
    attachments: ['logo_final_version.pdf'],
    created_at: '2026-04-07T10:15:00Z',
  },
  {
    id: 'msg_004',
    order_id: 'order_001',
    sender_id: 'user_admin_001',
    sender_role: 'admin',
    message: 'Thank you for working with us! Your feedback helps us improve. We look forward to your next order!',
    attachments: [],
    created_at: '2026-03-11T09:00:00Z',
  },
  {
    id: 'msg_005',
    order_id: 'order_002',
    sender_id: 'user_admin_001',
    sender_role: 'admin',
    message: 'Quality inspection report attached. All 250 bottles passed inspection with zero defects.',
    attachments: ['quality_inspection_report.pdf'],
    created_at: '2026-03-28T08:45:00Z',
  },
];

export const DEMO_SPECIFICATIONS: OrderSpecification[] = [
  {
    id: 'spec_001',
    order_id: 'order_001',
    materials: '100% cotton, pre-shrunk',
    colors: ['White', 'Navy Blue', 'Charcoal Gray'],
    logo_placement: 'Centered chest print',
    packaging_requirements: 'Individually folded, packed in boxes of 50',
    certifications: ['OEKO-TEX Standard 100'],
    additional_specs: {
      size_range: 'XS - 3XL',
      thread_color: 'White and Navy',
      wash_care: 'Machine wash warm, tumble dry low',
    },
  },
  {
    id: 'spec_002',
    order_id: 'order_002',
    materials: '18/8 stainless steel',
    colors: ['Blue', 'White', 'Black'],
    logo_placement: 'Full-wrap print',
    packaging_requirements: 'Foam padding, individual boxes with logo imprint',
    certifications: ['BPA-free', 'FDA approved'],
    additional_specs: {
      capacity: '16 oz',
      lid_type: 'Secure screw-on lid',
      insulation: 'Double-wall, keeps drinks cold for 24 hours',
    },
  },
  {
    id: 'spec_003',
    order_id: 'order_003',
    materials: '12 oz natural canvas',
    colors: ['Natural', 'Navy', 'Black'],
    logo_placement: 'Screen print on front',
    packaging_requirements: 'Flat packed in bulk, tissue paper separator',
    certifications: ['GOTS certified organic cotton'],
    additional_specs: {
      handle_type: 'Reinforced double stitched',
      dimensions: '15" x 16" x 4"',
      weight_capacity: '25 lbs',
    },
  },
  {
    id: 'spec_004',
    order_id: 'order_004',
    materials: 'Braided nylon sleeve with copper connectors',
    colors: ['Black', 'White'],
    logo_placement: 'Centered on sleeve',
    packaging_requirements: 'Individually packaged with hang tags',
    certifications: ['USB 3.1 certified', 'CE marked'],
    additional_specs: {
      cable_length: '2 meters',
      charging_speed: '5A max current',
      durability: 'Tested for 10000+ bend cycles',
    },
  },
];
